api/urls.py
from django.urls import path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from api import views

app_name = 'api'

# https://www.django-rest-framework.org/
urlpatterns = [
    path ('v1/message/', views.message_list, name='message_list'),
    path ('v2/message/', views.MessageView.as_view(), name='message_list2'),
    path ('v3/message/', views.MessageListCreateView.as_view(), name='message_list3'),

    # swagger
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "schema/docs/",
        SpectacularSwaggerView.as_view(url_name="api:schema"),
        name="swagger-docs",
    ),
]

# Autmoatyczny klient na bazie schematu openAPI
# https://github.com/OpenAPITools/openapi-generator
# https://github.com/openapi-generators/openapi-python-client

form_app/urls.py
from django.urls import path

from form_app import views

app_name = 'form_app'

urlpatterns = [
    path("1/", views.form1, name="form1"),
    path("2/", views.form2, name="form2"),
    path("task-list/", views.task_list, name="task_list"),

    # C - CRUD
    path("task/create/", views.task_create_view, name="task_create_view"),
    # R - Read (widok listy)
    path("task/list/", views.task_list_view, name="task_list_view"),
    # R - Read (widok szczegółu)
    path("task/<int:pk>/", views.task_detail_view, name="task_detail_view"),
    # U - Update
    path("task/update/<int:pk>/", views.task_update_view, name="task_update_view"),
    # D - Delete
    path("task/delete/<int:pk>/", views.task_delete_view, name="task_delete_view"),

]

intro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("hello/", include("hello_app.urls")),
    path("form/", include("form_app.urls")),
    path("formsviews/", include("forms_and_views_app.urls")),
    path("crud/", include("crud_app.urls")),
    path("extras/", include("extras_app.urls")),
    path("accounts/", include("accounts.urls")),
    path("api/", include("api.urls")),
]

form_app/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

form_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from form_app.models import Task


TASKS = []

# formularz get
def form1(request):
    data = request.GET

    task = data.get('task')
    if task:
        TASKS.append(task)

    return render(request, "form_app/form1.html")

# formularz post
def form2(request):
    if request.method == "GET":
        return render(request, "form_app/form2.html")

    elif request.method == "POST":
        data = request.POST
        task = data.get('task')

        if task:
            TASKS.append(task)
            return redirect("form_app:task_list")

        return render(request, "form_app/form2.html")
    else:
        return HttpResponse(status=405)


def task_list(request):
    return render(
        request,
        "form_app/task_list.html",
        {"tasks": TASKS}
    )


def task_create_view(request):
    if request.method == "GET":
        return render(request, "form_app/task_form.html")

    elif request.method == "POST":
        data = request.POST
        new_task = data.get('task')

        if new_task:
            Task.objects.create(name=new_task)
            return redirect("form_app:task_list_view")

        return render(request, "form_app/task_form.html")
    else:
        return HttpResponse(status=405)


def task_list_view(request):
    return render(
        request,
        "form_app/task_list.html",
        {"tasks": Task.objects.all()}
    )


def task_detail_view(request, pk):
    task = get_object_or_404(Task, id=pk)

    return render(
        request,
        "form_app/task_detail.html",
        {"task": task}
    )


def task_update_view(request, pk):
    task = get_object_or_404(Task, id=pk)

    if request.method == "GET":
        return render(request, "form_app/task_update.html", {"task": task})

    elif request.method == "POST":
        data = request.POST
        new_task = data.get('task')

        if new_task:
            task.name = new_task
            task.save()
            return redirect("form_app:task_list_view")

        return render(request, "form_app/task_update.html", {"task": task})
    else:
        return HttpResponse(status=405)


def task_delete_view(request, pk):
    task = get_object_or_404(Task, id=pk)

    if request.method == "GET":
        return render(
            request,
            "form_app/task_confirm_delete.html",
            {"task": task}
        )
    elif request.method == "POST":
        data = request.POST

        if 'confirm' in data:
            task.delete()

            return redirect("form_app:task_list_view")

        return render(request, "form_app/task_confirm_delete.html", {"task": task})

    else:
        return HttpResponse(status=405)

form_app/templates/form_app/form1.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Document</title>
</head>
<body>
    <form>
        <input type="text" name="task" placeholder="task">
        <input type="submit" value="Zapisz">
    </form>
</body>
</html>

form_app/templates/form_app/form2.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Document</title>
</head>
<body>
    <form method="POST">{% csrf_token %}
        <input type="text" name="task" placeholder="task">
        <input type="submit" value="Zapisz">
    </form>
</body>
</html>

form_app/templates/form_app/task_confirm_delete.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Document</title>
</head>
<body>
    Czy chcesz usunąć task o id {{ task.id }} [{{ task.name }}]
    <form method="POST">{% csrf_token %}
        <input type="submit" name="confirm" value="Tak">
        <a href="{% url 'form_app:task_list_view' %}"><button type="button">Anuluj</button></a>
    </form>
</body>
</html>

form_app/templates/form_app/task_detail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Document</title>
</head>
<body>
    <h2>Zadanie o id {{ task.id }}</h2>
    <p>{{ task }}</p>
    <a href="{% url 'form_app:task_list_view' %}"><button>Lista zadań</button></a>
</body>
</html>

form_app/templates/form_app/task_form.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Document</title>
</head>
<body>
    <form method="POST">{% csrf_token %}
        <input type="text" name="task" placeholder="task">
        <input type="submit" value="Zapisz">
    </form>
</body>
</html>

form_app/templates/form_app/task_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Document</title>
</head>
<body>
    <ol>
        {% for task in tasks %}
            <li>
                <a href="{% url 'form_app:task_detail_view' task.id %}">{{ task.name }}</a>
                <a href="{% url 'form_app:task_update_view' task.id %}"><button>Edytuj</button></a>
                <a href="{% url 'form_app:task_delete_view' task.id %}"><button>Usuń</button></a>
            </li>

        {% endfor %}
    </ol>
    <a href="{% url 'form_app:task_create_view' %}"><button>Nowe zadanie</button></a>
</body>
</html>

form_app/templates/form_app/task_update.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Document</title>
</head>
<body>
    <h2>Edycja taska o id {{ task.id }}</h2>
    <form method="POST">{% csrf_token %}
        <input type="text" name="task" placeholder="task" value="{{ task.name }}">
        <input type="submit" value="Zapisz">
    </form>
    <p>
        <a href="{% url 'form_app:task_list_view' %}"><button>Lista zadań</button></a>
    </p>
</body>
</html>