accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path("home/", views.home, name="home"),
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]

api/urls.py
from django.urls import path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from api import views

app_name = 'api'

# https://www.django-rest-framework.org/
urlpatterns = [
    path ('v1/message/', views.message_list, name='message_list'),
    path ('v2/message/', views.MessageView.as_view(), name='message_list2'),
    path ('v3/message/', views.MessageListCreateView.as_view(), name='message_list3'),

    # swagger
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "schema/docs/",
        SpectacularSwaggerView.as_view(url_name="api:schema"),
        name="swagger-docs",
    ),
]

# Autmoatyczny klient na bazie schematu openAPI
# https://github.com/OpenAPITools/openapi-generator
# https://github.com/openapi-generators/openapi-python-client

intro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("hello/", include("hello_app.urls")),
    path("form/", include("form_app.urls")),
    path("formsviews/", include("forms_and_views_app.urls")),
    path("crud/", include("crud_app.urls")),
    path("extras/", include("extras_app.urls")),
    path("accounts/", include("accounts.urls")),
    path("api/", include("api.urls")),
]

accounts/views.py
from django.shortcuts import render, HttpResponse, redirect

from django.contrib.auth import get_user_model, authenticate, login, logout
from django.views.decorators.http import require_http_methods

User = get_user_model()


def home(request):
    return render(
        request,
        "accounts/home.html",
    )


def register_view(request):
    if request.method == "GET":
        return render(
            request,
            "accounts/register.html"
        )
    if request.method == "POST":
        data = request.POST

        username = data.get("username")
        email = data.get("email")
        password1 = data.get("password1")
        password2 = data.get("password2")

        if password1 != password2:
            return HttpResponse("Podane hasła nie pasują do siebie")

        User.objects.create_user(
            username=username,
            email=email,
            password=password1
        )

        return redirect("accounts:home")


def login_view(request):
    if request.method == "GET":
        return render(
            request,
            "accounts/login.html"
        )
    if request.method == "POST":
        data = request.POST

        username = data.get("username")
        password = data.get("password")

        if not username or not password:
            return HttpResponse("Podano nieprawidłowe dane")

        # uwierzytelnienie
        user = authenticate(
            username=username,
            password=password
        )

        if user:
            # logowanie (mechanizm sesji)
            login(request, user)

        return redirect("accounts:home")


@require_http_methods(["POST"])
def logout_view(request):
    logout(request)
    return redirect("accounts:home")

accounts/templates/accounts/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if user.is_authenticated %}
        Witaj {{ user.username }}!
        <form method="POST" action="{%  url 'accounts:logout' %}">{% csrf_token %}
            <input type="submit" value="Wyloguj">
        </form>
    {% else %}
        <a href="{% url 'accounts:login' %}"><button>Zaloguj</button></a>
    {%  endif %}
</body>
</html>

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="POST">{% csrf_token %}
        <input type="text" name="username" id="username" placeholder="username">
        <input type="password" name="password" id="password" placeholder="password">
        <input type="submit" value="Zaloguj">
    </form>
</body>
</html>

accounts/templates/accounts/register.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Document</title>
</head>
<body>
    <form method="POST">{% csrf_token %}
        <input type="text" name="username" id="username" placeholder="username">
        <input type="email" name="email" id="email" placeholder="email">
        <input type="password" name="password1" id="password" placeholder="password">
        <input type="password" name="password2" id="password" placeholder="password">
        <input type="submit" value="Zarejestruj">
    </form>
</body>
</html>