api/urls.py
from django.urls import path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from api import views

app_name = 'api'

# https://www.django-rest-framework.org/
urlpatterns = [
    path ('v1/message/', views.message_list, name='message_list'),
    path ('v2/message/', views.MessageView.as_view(), name='message_list2'),
    path ('v3/message/', views.MessageListCreateView.as_view(), name='message_list3'),

    # swagger
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "schema/docs/",
        SpectacularSwaggerView.as_view(url_name="api:schema"),
        name="swagger-docs",
    ),
]

# Autmoatyczny klient na bazie schematu openAPI
# https://github.com/OpenAPITools/openapi-generator
# https://github.com/openapi-generators/openapi-python-client

crud_app/urls.py
from django.urls import path

from crud_app import views

app_name = 'crud_app'

urlpatterns = [
    path('create/', views.BookCreateView.as_view(), name='book_create_view'),
    path('list/', views.BookListView.as_view(), name='book_list_view'),
    path('<int:pk>/', views.BookDetailView.as_view(), name='book_detail_view'),
    path('update/<int:pk>/', views.BookUpdateView.as_view(), name='book_update_view'),
    path('delete/<int:pk>/', views.BookDeleteView.as_view(), name='book_delete_view')
]

intro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("hello/", include("hello_app.urls")),
    path("form/", include("form_app.urls")),
    path("formsviews/", include("forms_and_views_app.urls")),
    path("crud/", include("crud_app.urls")),
    path("extras/", include("extras_app.urls")),
    path("accounts/", include("accounts.urls")),
    path("api/", include("api.urls")),
]

crud_app/models.py
from django.db import models
from django.urls import reverse

CATEGORIES = [
    (1, "Comedy"),
    (2, "Thriller"),
    (3, "Romance"),
]


class Book(models.Model):
    added = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=256)
    category = models.IntegerField(choices=CATEGORIES)
    price = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse('crud_app:book_list_view')

crud_app/forms.py
from django import forms

from crud_app.models import Book


class BookForm(forms.ModelForm):
    model = Book

crud_app/views.py
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.edit import DeleteView
from django.views.generic.edit import UpdateView
from django.views.generic.list import ListView

from crud_app.models import Book


class BookDetailView(DetailView):
    model = Book


class BookListView(ListView):
    model = Book


class BookCreateView(CreateView):
    model = Book
    fields = ['title', 'category', 'price']


class BookUpdateView(UpdateView):
    model = Book
    fields = ['title', 'category', 'price']


class BookDeleteView(DeleteView):
    model = Book
    success_url = reverse_lazy("crud_app:book_list_view")  # no bo gdzie indziej?

crud_app/templates/crud_app/book_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
        <form method="post">{% csrf_token %}
            <p>Czy jesteś pewien, że chcesz usunąć książkę "{{ object }}"?</p>
            <input type="submit" value="Potwierdź">
            <a href="{% url 'crud_app:book_list_view' %}"><button type="button">Anuluj</button></a>
        </form>
</body>
</html>

crud_app/templates/crud_app/book_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Książka</title>
</head>
<body>
<h2>Tytuł: {{ book.title }}</h2>
<h3>Kategoria: {{ book.get_category_display }}</h3>
<h3>Cena: {{ book.price }} $</h3>

<br/>
<br/>
<footer>{{ book.added }}</footer>
</body>
</html>

crud_app/templates/crud_app/book_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dodaj książkę</title>
</head>
<body>
<h1>Dodaj książkę</h1>
<form method="post"> {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Dodaj">
</form>
</body>
</html>

crud_app/templates/crud_app/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
</head>
<body style="margin:1%;">
    <ui>
    {% for book in object_list %}
        <li style="margin:0.5%;">
            {{ book.title }}
            <a href="{% url 'crud_app:book_delete_view' book.id %}">
                <button type="button" class="btn btn-danger">Usuń</button>
            </a>
        </li>
    {% endfor %}
    </ui>
</body>
</html>

crud_app/templates/crud_app/book_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dodaj książkę</title>
</head>
<body>
<h1>Dodaj książkę</h1>
<form method="post" action="{% url 'crud_app:book_update_view' %}"> {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Zapisz">
</form>
</body>
</html>